dataset:
  name: NAIP
  dataset_path: /mnt/e/WYM/dataset/naip/image/
  cache_dir: # path/to/your/cache
  class_weights: [31086629, 7394358538, 6553775583, 2635695465]
  ignored_label_inds: [0]
#  num_points: 65536*2
  test_result_folder: ./test
  use_cache: true
  steps_per_epoch_train: 2000
  steps_per_epoch_valid: 1049
model:
  name: UNet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  num_classes: 4
  ignored_label_inds: [0]
  in_channels: 4
pipeline:
  name: SemanticSegmentationImg
  optimizer:
    lr: 0.001
   # weight_decay: 0.0001
   # momentum: 0.9
  batch_size: 2
  num_workers: 2
  main_log_dir: ./logs
  max_epoch: 50
  save_ckpt_freq: 5
  scheduler_gamma: 0.9886
  test_batch_size: 8
  train_sum_dir: train_log
  val_batch_size: 2
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
